### ISSUE TITLE
File-Path-Bar issue in Gnome 3.30

### ISSUE THREAD

**Issue by AlexMitchellMus** [mythio/macterial#1]
I have updated my Antergos Gnu/Linux system to Gnome 3.30, and noticed that the Nautilus file-path-bar is rendering incorrectly using Macterial theme.

I believe that Gnome 3.30 has changed to way that the file path is structured in CSS. There is now a:
`.path-bar-box` CSS class for the whole bar, (as opposed to using: `.path-bar button` for each directory).

Macterial is a very lovely - clean theme, it would be nice to be able to have this 3.30 compatible.

**Comment by ghost** [comment]
Thank you @alcomposer. I will fix this issue in the upcoming updates

**Comment by AlexMitchellMus** [comment]
Thanks @mythio!

Just noticed that the newest Gnome 3.30.1 has changed something in the edge rounding css. I have noticed that my 'hack' now only shows square edges in the path-bar. In 3.30.0 they were rounded.

**Comment by ghost** [comment]
Yes @alcomposer I noticed the rounded border changes too.

**Comment by AlexMitchellMus** [comment]
Beyond strange, after a few `pacman` updates the borders are back to rounded!?
