### ISSUE TITLE
Problem with color in file manager.

### ISSUE THREAD

**Issue by nimura255** [mythio/macterial#4]
File manager's side bar doesn't show colors properly in full-screen mode. I'm running Arch-Linux with GNOME 3.30.2.
![2019-02-25 16-34-41](https://user-images.githubusercontent.com/44906325/53350360-f947f700-392f-11e9-8afa-38446c58942c.png)

**Comment by mythio** [comment]
Hey! Thanks for bringing up the issue! I will fix that in the upcoming
update.

**Comment by ghmanoj** [comment]
Yep, I also get this in Fedora 29, when I maximize the file manager...
![screenshot from 2019-03-03 21-46-21](https://user-images.githubusercontent.com/10175663/53707760-4d564e00-3dfe-11e9-862b-2b3df4841ed7.png)

**Comment by DmHertz** [comment]
Issue reproducible. Found something...
``$ cat -n `find /usr/ -type f -name "gtk.css" 2> /dev/null | grep macterial` | grep -i 'ff3b3b'``
  8556	    background-color: #FF3b3b;
  8600	    background-color: #FF3B3B;
  8643	    background-color: #FF3B3B;

**Comment by DmHertz** [comment]
Okay. I just tested. The solution is to replace #FF3B3B on the lines 8556, 8600 and 8643 to #3B3B3B.

**Comment by ghost** [comment]
@DmHertz create a pull request.

**Comment by ghost** [comment]
Okay its done.
Closing the issue.

**Comment by ghmanoj** [comment]
Thank you for fixing this bug... :+1:
