### ISSUE TITLE
dark background behind buttons of inactive windows

### ISSUE THREAD

**Issue by tim-hilt** [mythio/macterial#7]
I have changed `~/.config/gtk-3.0/gtk.css` to have
```
.titlebar {
     background: #1C1E1F;
}
```
to match some of my custom themed applications. However now, when a window is inactive, the buttons have a darker background color, then the one used above.

![Screenshot_20190430_073907](https://user-images.githubusercontent.com/16037579/56942434-114c1a80-6b1b-11e9-9a27-97df8fb7e650.png)

Can you tell me what i can do to prevent this look? I really like macterial so far, that's the only thing that i havent gotten to work for me.

**Comment by ghost** [comment]
Yes I've also experienced the same long ago. Not sure why this happens. But I guess you have to increase the title buttons roundness for the headerbars.

**Comment by zeparu** [comment]
i looked into the pngs of the window buttons, all buttons have a transparent background, just the inactive window controls have a black background, thats probably being cut away within the css file, wouldnt just replacing the pngs with ones with transparent background fix this?

**Comment by zeparu** [comment]
a quick change on those files seems to have fixed it for me, there is not darker background on window controls on inactive windows 
![grafik](https://user-images.githubusercontent.com/21054889/75327045-06b5fb00-587c-11ea-8bfc-0bfbe0476848.png)

**Comment by zeparu** [comment]
pull request is open, this one only changes the image files, no changes in the css for cutting out the border manually, but its displaying correctly now

**Comment by zeparu** [comment]
ok after a bit of trouble, this issue should be fixed now with #16 @tim-hilt

**Comment by ghost** [comment]
I am closing this issue with reference to #16
