### ISSUE TITLE
Closing Buttons in Activity Overview not displaying correctly

### ISSUE THREAD

**Issue by zeparu** [mythio/macterial#9]
![Bildschirmfoto vom 2019-12-21 19-37-15](https://user-images.githubusercontent.com/21054889/71312302-7c8b8980-2429-11ea-8c80-6739a9721cbe.png)   
issue should be visible in the screenshot, the background circle is weirdly cut, and when hovering over 2 buttons in different size are displaying at the same time

here is a neofetch dump for system info
```
██████████████████  ████████   zepar@zepar-pc 
██████████████████  ████████   -------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Kernel: 5.4.2-1-MANJARO 
████████           ████████   Uptime: 5 hours 
████████  ████████  ████████   Packages: 1287 (pacman) 
████████  ████████  ████████   Shell: zsh 5.7.1 
████████  ████████  ████████   Resolution: 2560x1440, 1920x1080 
████████  ████████  ████████   DE: GNOME 3.34.1 
████████  ████████  ████████   WM: Mutter 
████████  ████████  ████████   WM Theme: macterial 
████████  ████████  ████████   Theme: macterial [GTK2/3] 
████████  ████████  ████████   Icons: Papirus-Dark [GTK2/3] 
████████  ████████  ████████   Terminal: gnome-terminal 
                               CPU: AMD Ryzen 5 2600 (12) @ 3.400GHz 
                               GPU: NVIDIA GeForce GTX 1060 6GB 
                               Memory: 4641MiB / 16005MiB 
```

**Comment by andrescornejo** [comment]
Opened a pull request. I was having the same issue across multiple systems with different distros and GNOME versions. So I changed a bit of the css code.

If the pull request is accepted it should more or less look like this:
![Screenshot from 2020-02-25 21-14-13](https://user-images.githubusercontent.com/31871621/75308356-e18da200-5813-11ea-9deb-eb5cb2922618.png)

Which is what I think the creator originally intended it to look like.
I hope this helps.

Cheers.
